name: Asciidoctor PlantUML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Asciidoctor and PlantUML
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoctor graphviz default-jre-headless
        sudo gem install asciidoctor-diagram
    - name: Render Asciidoctor document with PlantUML
      run: |
        asciidoctor -r asciidoctor-diagram -a source-highlighter=rouge -a rouge-theme=github -a icons=font -a experimental=true -a imagesdir=images -a plantuml-server-url=https://www.plantuml.com/plantuml -a plantuml-format=svg -a plantuml-outputdir=images -a plantuml-diagram-include=.* -a plantuml-include=.* -a plantuml-allow-include=true -a plantuml-verbose=true -a plantuml-max-retry=5 -a plantuml-retry-delay=2 -a plantuml-fetch-timeout=30 -a plantuml-parallel=true -a plantuml-parallel-threads=4 -a plantuml-parallel-jobs=2 -a plantuml-parallel-queue=10 -a plantuml-parallel-queue-timeout=60 -a plantuml-parallel-queue-retry=5 -a plantuml-parallel-queue-retry-delay=2 -a plantuml-parallel-queue-retry-max=5 -a plantuml-parallel-queue-retry-max-delay=10 -a plantuml-parallel-queue-retry-max-timeout=300 -a plantuml-parallel-queue-retry-max-retry=5 -a plantuml-parallel-queue-retry-max-retry-delay=2 -a plantuml-parallel-queue-retry-max-retry-max=5 -a plantuml-parallel-queue-retry-max-retry-max